# Generated by Django 4.1.7 on 2023-07-05 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='colaborators', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('morning_activity', models.TextField(blank=True, null=True)),
                ('afternoon_activity', models.TextField(blank=True, null=True)),
                ('evening_activity', models.TextField(blank=True, null=True)),
                ('morning_budget', models.IntegerField(default=0)),
                ('afternoon_budget', models.IntegerField(default=0)),
                ('evening_budget', models.IntegerField(default=0)),
                ('morning_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('morning_long', models.FloatField(blank=True, default=0.0, null=True)),
                ('afternoon_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('afternoon_long', models.FloatField(blank=True, default=0.0, null=True)),
                ('evening_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('evening_long', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itinerary')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
