# Generated by Django 4.1.7 on 2023-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_location_itinerary_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
