# Generated by Django 4.1.7 on 2023-07-13 15:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itinerary_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('overview', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='updated_by',
        ),
    ]
