# Generated by Django 4.1.7 on 2023-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_destination_remove_itineraryday_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('Rift Valley', 'Riftvalley'), ('Eastern', 'Eastern'), ('North Eastern', 'Northeastern'), ('Coast', 'Coast'), ('Central', 'Central'), ('Nairobi', 'Nairobi'), ('Nyanza', 'Nyanza'), ('Western', 'Western')], default='Nairobi', max_length=20),
        ),
    ]
